### PR TITLE
Idempotency

### LINKED ISSUE #19: `home-manager`: `error: opening lock file…`
Resolved by manually running the fix from https://github.com/juspay/nixos-unified-template?tab=readme-ov-file#error-opening-lock-file-

Error logs:
```sh
Writing syntax set to /Users/salokya.kumar/.cache/bat/syntaxes.bin ... okay
Writing metadata to folder /Users/salokya.kumar/.cache/bat ... okay
Activating installPackages
installing 'home-manager-path'
error: opening lock file '/nix/var/nix/profiles/per-user/salokya.kumar/profile.lock': No such file or directory

Oops, Nix failed to install your new Home Manager profile!

Perhaps there is a conflict with a package that was installed using
"nix-env -i"? Try running

    nix-env -q

and if there is a conflicting package you can remove it with

    nix-env -e {package name}

Then try activating your Home Manager configuration again.

# Initialize a git repo
```

what could be the cause? can we detect and fix this automatically in the script?

### PR DESCRIPTION
**Pull request by shivaraj-bh**
fixes https://github.com/juspay/nixone/issues/16
fixes https://github.com/juspay/nixone/issues/8
fixes #19

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
https://github.com/juspay/omnix/pull/404 is required to exit if `DetSys` nix installer is not used.

**Comment by shivaraj-bh** [comment]
## Pristine ubuntu

### First run
image

### Re-run (same terminal window)
We do explicitly tell users to start a new terminal, but from my experience, it is better to test this scenario too...
image

### Re-run (new terminal window)
image


Note to self: Get rid of `true` `false` noise at the end of the output

**Comment by shivaraj-bh** [comment]
## Pristine macOS VM

### First run
image

### Re-run (same terminal window)
image

### Re-run (new terminal window)
image

**Comment by shivaraj-bh** [comment]
Tested on macOS and Ubuntu to work idempotently.

File: setup.sh [hunk 1]
```diff
@@ -1,29 +1,47 @@
 #!/bin/sh
+# Check if nix is already installed
+if ! which nix > /dev/null 2>&1; then
```
Comment (srid) [inline setup.sh:3]: Is there a reason for sending STDER to `/dev/null`?

File: setup.sh [hunk 2]
```diff
@@ -1,29 +1,47 @@
...
+is_nix_healthy=$?
+
+echo $health_out | nix run nixpkgs#jq -- -e '.info.nix_installer.type == "DetSys"' > /dev/null
+is_detsys_used=$?
+
+if [ $is_nix_healthy -ne 0 ] && [ $is_detsys_used -ne 0 ]; then
+  echo "\n# Nix unhealthy"
+  echo "\n# Uninstall Nix: <https://nixos.asia/en/howto/uninstall-nix>. Post uninstall, re-run the script."
+  exit 1
+fi
```
Comment (srid) [inline setup.sh:26]: The code here is not self-explanatory as to why, for example, `om health` being unhealthy (say, trusted-users check failed or Nix version is old) must have the user uninstall Nix.

File: setup.sh (hunk 1 above)
Comment (shivaraj-bh) [reply setup.sh:3]: Nope, I will just pipe stdout.

File: setup.sh (hunk 2 above)
Comment (shivaraj-bh) [reply setup.sh]: I have added a comment now, also added a TODO to re-evaluate if suggesting Uninstall is too harsh.

Comment (shivaraj-bh) [reply setup.sh]: I was thinking if it is better to suggest uninstall only if rosetta check fails?

**Review by srid — APPROVED** [review]
